# Generated by Django 5.2.7 on 2025-10-10 23:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the subscriber', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the user subscribed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the subscriber', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser information of the subscriber', null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
